version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'employee'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - mysql-network
    volumes:
      - mysql:/var/lib/mysql

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=login
    ports:
        - '5432:5432'
    networks:
      - mysql-network
    volumes:
      - postgres:/var/lib/postgres

  employee-service:
    container_name: employee-service
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/employee
      - spring.datasource.username=user
      - spring.datasource.password=password
    build: 
      context: ./employee-service/
      dockerfile: Dockerfile
    # image: employeeService:latest
    ports: 
      - 8082:8082
    networks:
      - mysql-network
    depends_on:
      - mysql

  login-service:
    container_name: login-service
    restart: always
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/login
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=create
    build: 
      context: ./login-service/
      dockerfile: Dockerfile
    # image: LoginService:latest
    ports: 
      - 8081:8081
    networks:
      - mysql-network
    depends_on:
      - postgres

  api-gateway:
    container_name: api-gateway
    restart: always
    environment:
      - zuul.routes.login.path=/login/**
      - zuul.routes.login.url=http://127.0.0.1:8081/
      - zuul.routes.employee.path=/employee/**
      - zuul.routes.employee.url=http://127.0.0.1:8082/
      - ribbon.eureka.enabled=false
      - eureka.client.fetch-registry=false
      - eureka.client.register-with-eureka=false
    build: 
      context: ./api-gateway/
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    networks:
      - mysql-network
    depends_on:
      - employee-service
      - login-service

volumes:
  mysql:
  postgres:

networks:
  mysql-network:
    # driver: bridge
      
