version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'employee'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - employee-mysql
    volumes:
      - mysql:/var/lib/mysql

  mysql2:
    image: mysql:5.7
    restart: always
    container_name: mysql2
    environment:
        MYSQL_DATABASE: 'login'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - '3307:3306'
    # networks:
    #     - login-mysql
    volumes:
        - mysql2:/var/lib/mysql2

  employee-service:
    container_name: employee-service
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/employee
      - spring.datasource.username=user
      - spring.datasource.password=password
    image: fullstackcodingchallenge:latest
    ports: 
      - 8082:8082
    networks:
      - employee-mysql
    depends_on:
      - mysql



volumes:
  mysql:
  mysql2:

networks:
  employee-mysql:
      
